[workspace]
resolver = "2"
members = [
    "psp-rt",
    "psp-tc",
    "usbhostfs-sys",
    "psplink-connection",
    "audio-recorder",
    "examples/mnist-bench/device",
    "examples/mnist-bench/host",
    "examples/hello-psp/device",
    "examples/hello-psp/host",
    "examples/birdnet/device",
    "examples/birdnet/host",
    "examples/meminfo/device",
    "examples/meminfo/host",
    "examples/profiler-demo/device",
    "examples/profiler-demo/host",
]
default-members = [
    "psp-rt",
    "examples/mnist-bench/device",
    "examples/mnist-bench/host",
]
