[package]
name = "vme-conformance-host"
edition = "2021"
default-run = "vme-conformance-host"

[[bin]]
name = "vme-conformance-host"
path = "src/main.rs"

[dependencies]
psplink-connection = { path = "../../../toolchain/psplink-connection" }
vme-assembler = { path = "../../../toolchain/psp-tc/vme-assembler" }
vme-emu-sys = { path = "../../../toolchain/vme-emu-sys" }

[[bin]]
name = "vme-skew-probe"
path = "src/bin/probe.rs"
