[package]
name = "birdnet"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "birdnet"
path = "src/main.rs"

[features]
default = []
local = []

[dependencies]
psp-rt = { path = "../../../psp-rt" }

[target.'cfg(target_os = "psp")'.dependencies]
psp = "0.3"

[build-dependencies]
psp-tc = { path = "../../../psp-tc" }
