[package]
name = "vme-conv-bench"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "vme-conv-bench"
path = "src/main.rs"

[dependencies]
psp-rt = { path = "../../../toolchain/psp-rt" }

[target.'cfg(target_os = "psp")'.dependencies]
psp = "0.3"

[build-dependencies]
psp-tc = { path = "../../../toolchain/psp-tc" }
