//! # psp-ml
//!
//! Runtime library for PSP machine learning inference.
//!
//! Provides kernel implementations used by code generated by `cargo-psp-ml`.
//! This crate is `no_std` — it runs on the PSP (and on host for local testing).

#![no_std]
#![cfg_attr(target_os = "psp", feature(asm_experimental_arch))]

pub mod kernels;
