//! # psp-ml
//!
//! Runtime library for PSP machine learning inference.
//!
//! Provides kernel implementations used by code generated by `cargo-psp-ml`.
//! This crate is `no_std` — it runs on the PSP (and on host for local testing).

#![no_std]
#![cfg_attr(target_os = "psp", feature(asm_experimental_arch))]

pub mod bench;
pub mod kernels;
pub mod print;

/// Declare a PSP module.
///
/// Wraps `psp::module!` and generates a `psp_main()` that calls your
/// `app_main()` function.
///
/// ```ignore
/// psp_ml::module!("hello_psp", 1, 0);
///
/// fn app_main() {
///     psp_ml::dprintln!("Hello from PSP!");
/// }
/// ```
#[macro_export]
macro_rules! module {
    ($name:expr, $version_major:expr, $version_minor:expr) => {
        fn psp_main() {
            app_main();
        }

        psp::module!($name, $version_major, $version_minor);
    };
}
