//! # psp-rt
//!
//! Runtime library for PSP homebrew: module bootstrapping (`module!`),
//! print macros routed over psplink (`print`), hardware profiler bindings
//! (`profiler`), and VFPU-accelerated ML kernels (`kernels`) used by code
//! generated by `psp-tc`. This crate is `no_std` — it runs on the PSP (and
//! on host for local testing).

#![no_std]
#![cfg_attr(target_os = "psp", feature(asm_experimental_arch))]
// `vfpu_asm!` expands one macro recursion per instruction; the 4x8 GEMM
// micro-kernel is ~70 instructions in a single block, well past the default 128.
#![recursion_limit = "1024"]

pub mod kernels;
pub mod mem;
pub mod print;
pub mod profiler;

/// Declare a PSP module.
///
/// Generates a `psp_main()` that calls your `app_main()` function, and the
/// module's `SceModuleInfo`/entry-table boilerplate, same shape as
/// `psp::module!` — but does **not** delegate to `psp::module!` for the
/// `module_start` entry point itself. This is deliberate: `psp::module!`
/// (see `psp-0.3.13/src/lib.rs:241-262`) spawns the user's code on a
/// separate `main_thread` and returns from `module_start` immediately,
/// without waiting for it. The PSP kernel's ModuleManager only ever
/// `sceKernelWaitThreadEnd`s on `module_start`'s own thread
/// (`uofw/src/kd/modulemgr/modulemgr.c:1182-1195`), so with the upstream
/// behavior, psplink's `ld` shell command reports "done" almost instantly
/// — before `app_main` has necessarily printed anything, let alone
/// finished. `psplink-connection::load_program` needs that completion
/// signal to actually mean something, so `module_start` here blocks on the
/// worker thread via `sceKernelWaitThreadEnd` instead.
///
/// That surfaces a second issue: the PSP kernel treats a `module_start`
/// return value of exactly `0` as `SCE_KERNEL_RESIDENT` — "keep the module
/// loaded, don't tear it down" (`uofw/include/common/module.h:126,129`).
/// Waiting-then-returning-0 was tried and empirically confirmed (on real
/// hardware, this session) to leak a resident module instance per `ld`
/// call. So the exit-status convention here is chosen to never return `0`:
///
/// - `1` (`SCE_KERNEL_NO_RESIDENT`) — `app_main` returned normally. The
///   kernel unloads the module and this collapses to a generic
///   `SCE_ERROR_OK` (`0x0`) by the time it reaches the shell channel
///   (`modulemgr.c:249-250`).
/// - `psplink_connection`'s `PANIC_SENTINEL` (`0xFFFF_FFFF`) — `app_main`
///   panicked, caught by `catch_unwind`. Passed through raw
///   (`modulemgr.c:251-253`), so `psplink-connection` can tell it apart
///   from a clean exit.
///
/// `app_main() -> ()` stays infallible for now — there's no way to plumb a
/// real exit code through without colliding with `0`/`1`/the panic
/// sentinel, and nothing needs one yet. If that's ever needed, the natural
/// extension is `app_main() -> i32`, biasing user codes to avoid those
/// three reserved values.
///
/// ```ignore
/// psp_rt::module!("hello_psp", 1, 0);
///
/// fn app_main() {
///     psp_rt::dprintln!("Hello from PSP!");
/// }
/// ```
#[macro_export]
macro_rules! module {
    ($name:expr, $version_major:expr, $version_minor:expr) => {
        $crate::__module_impl!($name, $version_major, $version_minor, 0);
    };

    ($name:expr, $version_major:expr, $version_minor:expr, $mod_attr:expr) => {
        $crate::__module_impl!($name, $version_major, $version_minor, $mod_attr);
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __module_impl {
    ($name:expr, $version_major:expr, $version_minor:expr, $mod_attr:expr) => {
        fn psp_main() {
            app_main();
        }

        #[doc(hidden)]
        mod __psp_module {
            #[no_mangle]
            #[link_section = ".rodata.sceModuleInfo"]
            #[used]
            static MODULE_INFO: ::psp::Align16<::psp::sys::SceModuleInfo> =
                ::psp::Align16(::psp::sys::SceModuleInfo {
                    mod_attribute: $mod_attr,
                    mod_version: [$version_major, $version_minor],
                    mod_name: ::psp::sys::SceModuleInfo::name($name),
                    terminal: 0,
                    gp_value: unsafe { &_gp },
                    stub_top: unsafe { &__lib_stub_top },
                    stub_end: unsafe { &__lib_stub_bottom },
                    ent_top: unsafe { &__lib_ent_top },
                    ent_end: unsafe { &__lib_ent_bottom },
                });

            extern "C" {
                static _gp: u8;
                static __lib_ent_bottom: u8;
                static __lib_ent_top: u8;
                static __lib_stub_bottom: u8;
                static __lib_stub_top: u8;
            }

            #[no_mangle]
            #[link_section = ".lib.ent"]
            #[used]
            static LIB_ENT: ::psp::sys::SceLibraryEntry = ::psp::sys::SceLibraryEntry {
                name: core::ptr::null(),
                version: ($version_major, $version_minor),
                attribute: ::psp::sys::SceLibAttr::SCE_LIB_IS_SYSLIB,
                entry_len: 4,
                var_count: 1,
                func_count: 1,
                entry_table: &LIB_ENT_TABLE,
            };

            #[no_mangle]
            #[link_section = ".rodata.sceResident"]
            #[used]
            static LIB_ENT_TABLE: ::psp::sys::SceLibraryEntryTable =
                ::psp::sys::SceLibraryEntryTable {
                    module_start_nid: 0xd632acdb, // module_start
                    module_info_nid: 0xf01d73a7,  // SceModuleInfo
                    module_start: module_start,
                    module_info: &MODULE_INFO.0,
                };

            use core::ffi::c_void;

            /// See never-return-0 convention documented on `psp_rt::module!`.
            const PSP_RT_NO_RESIDENT: i32 = 1;
            const PSP_RT_PANIC_STATUS: i32 = -1_i32; // 0xFFFF_FFFF as u32 — psplink_connection::load::PANIC_SENTINEL

            #[no_mangle]
            extern "C" fn module_start(argc_bytes: usize, argv: *mut c_void) -> isize {
                extern "C" fn main_thread(argc: usize, argv: *mut c_void) -> i32 {
                    unsafe fn init_cwd(arg0: *mut u8) {
                        let mut len = 0;
                        while *arg0.add(len) != 0 {
                            len += 1;
                        }

                        // Truncate until last '/'
                        while len > 0 && *arg0.add(len - 1) != b'/' {
                            len -= 1;
                        }

                        if len > 0 {
                            let tmp = *arg0.add(len);
                            *arg0.add(len) = 0;
                            ::psp::sys::sceIoChdir(arg0 as *const u8);
                            *arg0.add(len) = tmp;
                        }
                    }

                    if argc > 0 {
                        unsafe { init_cwd(argv as *mut u8) };
                    }

                    let status = match ::psp::catch_unwind(super::psp_main) {
                        Ok(()) => PSP_RT_NO_RESIDENT,
                        Err(_) => PSP_RT_PANIC_STATUS,
                    };
                    // Partition blocks are not reclaimed on module unload
                    // under psplink; drain the tracked-allocation registry on
                    // both the clean and the panic path so repeated `ld`s
                    // can't exhaust the pool.
                    $crate::mem::free_all();
                    status
                }

                unsafe {
                    let id = ::psp::sys::sceKernelCreateThread(
                        b"main_thread\0".as_ptr(),
                        main_thread,
                        // default priority of 32.
                        32,
                        // 256kb stack
                        256 * 1024,
                        ::psp::sys::ThreadAttributes::USER | ::psp::sys::ThreadAttributes::VFPU,
                        core::ptr::null_mut(),
                    );

                    ::psp::sys::sceKernelStartThread(id, argc_bytes, argv);
                    ::psp::sys::sceKernelWaitThreadEnd(id, core::ptr::null_mut()) as isize
                }
            }
        }
    };
}
