//! # psp-rt
//!
//! Runtime library for PSP homebrew: module bootstrapping (`module!`),
//! print macros routed over psplink (`print`), hardware profiler bindings
//! (`profiler`), and VFPU-accelerated ML kernels (`kernels`) used by code
//! generated by `psp-tc`. This crate is `no_std` — it runs on the PSP (and
//! on host for local testing).

#![no_std]
#![cfg_attr(target_os = "psp", feature(asm_experimental_arch))]
// `vfpu_asm!` expands one macro recursion per instruction; the 4x8 GEMM
// micro-kernel is ~70 instructions in a single block, well past the default 128.
#![recursion_limit = "1024"]

pub mod device_test;
pub mod kernels;
pub mod mem;
pub mod print;
pub mod profiler;
pub mod vme;

/// Thread id of the home-button watcher, so it can be reaped at exit.
///
/// `psp::enable_home_button` discards it, which is why this crate has its own.
#[cfg(target_os = "psp")]
static mut HOME_BUTTON_THID: ::psp::sys::SceUid = ::psp::sys::SceUid(-1);

/// Enable exiting a running app with the HOME button.
///
/// Same behaviour as `psp::enable_home_button`, but it remembers the watcher
/// thread so `module!` can reap it. Upstream's version creates a thread with a
/// 4 KiB stack whose body ends in `sceKernelSleepThreadCB()` — it never
/// returns, so it is never deleted, and its stack leaks on every `ld`. That is
/// the entire 4,096 B residual left after the worker-thread fix.
///
/// Device crates should call this instead of `psp::enable_home_button`.
#[cfg(target_os = "psp")]
pub fn enable_home_button() {
    use ::psp::sys;
    use core::{ffi::c_void, ptr};

    unsafe extern "C" fn exit_thread(_args: usize, _argp: *mut c_void) -> i32 {
        unsafe extern "C" fn exit_callback(_a1: i32, _a2: i32, _arg: *mut c_void) -> i32 {
            unsafe { sys::sceKernelExitGame() };
            0
        }
        unsafe {
            let cb = sys::sceKernelCreateCallback(
                &b"exit_callback\0"[0],
                exit_callback,
                ptr::null_mut(),
            );
            sys::sceKernelRegisterExitCallback(cb);
            // Blocks forever waiting for the callback, so this thread has to be
            // terminated rather than joined.
            sys::sceKernelSleepThreadCB();
        }
        0
    }

    unsafe {
        let id = sys::sceKernelCreateThread(
            &b"exit_thread\0"[0],
            exit_thread,
            32,
            0x1000,
            sys::ThreadAttributes::empty(),
            ptr::null_mut(),
        );
        if id.0 >= 0 {
            HOME_BUTTON_THID = id;
            sys::sceKernelStartThread(id, 0, ptr::null_mut());
        }
    }
}

/// Reap the threads `module!` is responsible for.
///
/// A PSP thread that returns from its entry point goes *dormant*, not away —
/// its stack stays allocated until `sceKernelDeleteThread`. Two threads were
/// leaking this way on every `ld`, for a measured 266,240 B per load
/// independent of module size
///
/// | thread | stack | reaped by |
/// |---|---|---|
/// | `module!`'s worker | 262,144 B | `sceKernelDeleteThread` (dormant) |
/// | `enable_home_button`'s watcher | 4,096 B | `sceKernelTerminateDeleteThread` |
///
/// The watcher has to be *terminated* rather than deleted: its body ends in
/// `sceKernelSleepThreadCB()`, so it never becomes dormant on its own.
///
/// `dormant` says whether the worker exited by itself. On the timeout path it
/// is still running and must be terminated instead.
///
/// The `leak-thread` feature restores the old behaviour so the leak can be
/// measured against the fix on hardware. The feature gate is *here* and not in
/// the `module!` body because `#[cfg(feature = ...)]` inside a `macro_rules!`
/// is evaluated in the crate the macro expands into, which would silently test
/// the device crate's features instead.
#[doc(hidden)]
#[cfg(target_os = "psp")]
pub fn __reap_threads(worker: ::psp::sys::SceUid, dormant: bool) {
    #[cfg(not(feature = "leak-thread"))]
    unsafe {
        if dormant {
            ::psp::sys::sceKernelDeleteThread(worker);
        } else {
            ::psp::sys::sceKernelTerminateDeleteThread(worker);
        }
        // Harmless if the watcher was never started.
        if HOME_BUTTON_THID.0 >= 0 {
            ::psp::sys::sceKernelTerminateDeleteThread(HOME_BUTTON_THID);
            HOME_BUTTON_THID = ::psp::sys::SceUid(-1);
        }
    }
    #[cfg(feature = "leak-thread")]
    let _ = (worker, dormant);
}

/// Declare a PSP module.
///
/// Generates a `psp_main()` that calls your `app_main()` function, and the
/// module's `SceModuleInfo`/entry-table boilerplate, same shape as
/// `psp::module!` — but does **not** delegate to `psp::module!` for the
/// `module_start` entry point itself. This is deliberate: `psp::module!`
/// (see `psp-0.3.13/src/lib.rs:241-262`) spawns the user's code on a
/// separate `main_thread` and returns from `module_start` immediately,
/// without waiting for it. The PSP kernel's ModuleManager only ever
/// `sceKernelWaitThreadEnd`s on `module_start`'s own thread
/// (`uofw/src/kd/modulemgr/modulemgr.c:1182-1195`), so with the upstream
/// behavior, psplink's `ld` shell command reports "done" almost instantly
/// — before `app_main` has necessarily printed anything, let alone
/// finished. `psplink-connection::load_program` needs that completion
/// signal to actually mean something, so `module_start` here blocks on the
/// worker thread via `sceKernelWaitThreadEnd` instead.
///
/// That surfaces a second issue: the PSP kernel treats a `module_start`
/// return value of exactly `0` as `SCE_KERNEL_RESIDENT` — "keep the module
/// loaded, don't tear it down" (`uofw/include/common/module.h:126,129`).
/// Waiting-then-returning-0 was tried and empirically confirmed (on real
/// hardware, this session) to leak a resident module instance per `ld`
/// call. So the exit-status convention here is chosen to never return `0`:
///
/// - `1` (`SCE_KERNEL_NO_RESIDENT`) — `app_main` returned normally. The
///   kernel unloads the module and this collapses to a generic
///   `SCE_ERROR_OK` (`0x0`) by the time it reaches the shell channel
///   (`modulemgr.c:249-250`).
/// - `psplink_connection`'s `PANIC_SENTINEL` (`0xFFFF_FFFF`) — `app_main`
///   panicked, caught by `catch_unwind`. Passed through raw
///   (`modulemgr.c:251-253`), so `psplink-connection` can tell it apart
///   from a clean exit.
///
/// `app_main() -> ()` stays infallible for now — there's no way to plumb a
/// real exit code through without colliding with `0`/`1`/the panic
/// sentinel, and nothing needs one yet. If that's ever needed, the natural
/// extension is `app_main() -> i32`, biasing user codes to avoid those
/// three reserved values.
///
/// ```ignore
/// psp_rt::module!("hello_psp", 1, 0);
///
/// fn app_main() {
///     psp_rt::dprintln!("Hello from PSP!");
/// }
/// ```
#[macro_export]
macro_rules! module {
    ($name:expr, $version_major:expr, $version_minor:expr) => {
        $crate::__module_impl!($name, $version_major, $version_minor, 0);
    };

    ($name:expr, $version_major:expr, $version_minor:expr, $mod_attr:expr) => {
        $crate::__module_impl!($name, $version_major, $version_minor, $mod_attr);
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __module_impl {
    ($name:expr, $version_major:expr, $version_minor:expr, $mod_attr:expr) => {
        fn psp_main() {
            app_main();
        }

        #[doc(hidden)]
        mod __psp_module {
            #[no_mangle]
            #[link_section = ".rodata.sceModuleInfo"]
            #[used]
            static MODULE_INFO: ::psp::Align16<::psp::sys::SceModuleInfo> =
                ::psp::Align16(::psp::sys::SceModuleInfo {
                    mod_attribute: $mod_attr,
                    mod_version: [$version_major, $version_minor],
                    mod_name: ::psp::sys::SceModuleInfo::name($name),
                    terminal: 0,
                    gp_value: unsafe { &_gp },
                    stub_top: unsafe { &__lib_stub_top },
                    stub_end: unsafe { &__lib_stub_bottom },
                    ent_top: unsafe { &__lib_ent_top },
                    ent_end: unsafe { &__lib_ent_bottom },
                });

            extern "C" {
                static _gp: u8;
                static __lib_ent_bottom: u8;
                static __lib_ent_top: u8;
                static __lib_stub_bottom: u8;
                static __lib_stub_top: u8;
            }

            #[no_mangle]
            #[link_section = ".lib.ent"]
            #[used]
            static LIB_ENT: ::psp::sys::SceLibraryEntry = ::psp::sys::SceLibraryEntry {
                name: core::ptr::null(),
                version: ($version_major, $version_minor),
                attribute: ::psp::sys::SceLibAttr::SCE_LIB_IS_SYSLIB,
                entry_len: 4,
                var_count: 1,
                func_count: 1,
                entry_table: &LIB_ENT_TABLE,
            };

            #[no_mangle]
            #[link_section = ".rodata.sceResident"]
            #[used]
            static LIB_ENT_TABLE: ::psp::sys::SceLibraryEntryTable =
                ::psp::sys::SceLibraryEntryTable {
                    module_start_nid: 0xd632acdb, // module_start
                    module_info_nid: 0xf01d73a7,  // SceModuleInfo
                    module_start: module_start,
                    module_info: &MODULE_INFO.0,
                };

            use core::ffi::c_void;

            /// See never-return-0 convention documented on `psp_rt::module!`.
            const PSP_RT_NO_RESIDENT: i32 = 1;
            const PSP_RT_PANIC_STATUS: i32 = -1_i32; // 0xFFFF_FFFF as u32 — psplink_connection::load::PANIC_SENTINEL
            /// `app_main` overran its budget and was killed.
            const PSP_RT_TIMEOUT_STATUS: i32 = 2;
            /// Wall-clock budget for `app_main`. Generous — the slowest thing
            /// in-tree is ~30 s — because the only cost of a high limit is how
            /// long you wait on a genuinely hung run.
            const PSP_RT_TIMEOUT_SECS: u32 = 240;

            /// Set by `main_thread` just before it returns; read by
            /// `module_start` after the wait.
            static mut APP_STATUS: i32 = PSP_RT_TIMEOUT_STATUS;

            #[no_mangle]
            extern "C" fn module_start(argc_bytes: usize, argv: *mut c_void) -> isize {
                extern "C" fn main_thread(argc: usize, argv: *mut c_void) -> i32 {
                    unsafe fn init_cwd(arg0: *mut u8) {
                        let mut len = 0;
                        while *arg0.add(len) != 0 {
                            len += 1;
                        }

                        // Truncate until last '/'
                        while len > 0 && *arg0.add(len - 1) != b'/' {
                            len -= 1;
                        }

                        if len > 0 {
                            let tmp = *arg0.add(len);
                            *arg0.add(len) = 0;
                            ::psp::sys::sceIoChdir(arg0 as *const u8);
                            *arg0.add(len) = tmp;
                        }
                    }

                    if argc > 0 {
                        unsafe { init_cwd(argv as *mut u8) };
                    }

                    let status = match ::psp::catch_unwind(super::psp_main) {
                        Ok(()) => PSP_RT_NO_RESIDENT,
                        Err(_) => PSP_RT_PANIC_STATUS,
                    };
                    // Partition blocks are not reclaimed on module unload
                    // under psplink; drain the tracked-allocation registry on
                    // both the clean and the panic path so repeated `ld`s
                    // can't exhaust the pool.
                    $crate::mem::free_all();
                    // Publish the status here rather than relying on
                    // `sceKernelWaitThreadEnd`'s return value, whose meaning
                    // (thread exit status vs plain 0/-errno) differs between
                    // references. Reading it back from a static makes the
                    // panic sentinel reach the host deterministically.
                    unsafe { APP_STATUS = status };
                    status
                }

                unsafe {
                    let id = ::psp::sys::sceKernelCreateThread(
                        b"main_thread\0".as_ptr(),
                        main_thread,
                        // default priority of 32.
                        32,
                        // 256kb stack
                        256 * 1024,
                        ::psp::sys::ThreadAttributes::USER | ::psp::sys::ThreadAttributes::VFPU,
                        core::ptr::null_mut(),
                    );

                    ::psp::sys::sceKernelStartThread(id, argc_bytes, argv);

                    // Bounded wait. Blocking `module_start` is what makes `ld`
                    // completion meaningful (see the macro docs), but it also
                    // makes psplink's shell thread hostage to this one: a hung
                    // or faulted `app_main` leaves `ld` outstanding forever,
                    // which neither `reset` nor a USB reset can clear — only
                    // physically power-cycling the PSP. A timeout on the wait
                    // itself needs no second thread and does not depend on the
                    // scheduler preempting a thread spinning in a tight loop.
                    let mut timeout_us: u32 = PSP_RT_TIMEOUT_SECS * 1_000_000;
                    let waited = ::psp::sys::sceKernelWaitThreadEnd(id, &mut timeout_us);

                    if waited < 0 {
                        // Timed out (or the wait itself failed) — the worker may
                        // still be running, and unloading the module out from
                        // under a live thread would fault. Kill it first.
                        $crate::dprintln!(
                            "\npsp-rt: app_main exceeded {} s, terminating",
                            PSP_RT_TIMEOUT_SECS
                        );
                        $crate::__reap_threads(id, false);
                        $crate::mem::free_all();
                        return PSP_RT_TIMEOUT_STATUS as isize;
                    }

                    // The worker has ended but is only dormant; reap it and the
                    // home-button watcher or their stacks leak. `APP_STATUS` is
                    // module .bss, not thread stack, so it outlives them.
                    $crate::__reap_threads(id, true);

                    APP_STATUS as isize
                }
            }
        }
    };
}
